export const RECEIVE_POKEMONS_COUNT = 'RECEIVE_POKEMONS_COUNT'
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS'
export const RECEIVE_PAGINATION = 'RECEIVE_PAGINATION'
export const RECEIVE_POKEMON = 'RECEIVE_POKEMON'
